import * as AUTHENTICATION from './AUTHENTICATION';
import * as SETUP_DATA from './SETUP_DATA';
import * as PENDAFTARAN_PASIEN from './PENDAFTARAN_PASIEN';
import * as PELAYANAN_PASIEN from './PELAYANAN_PASIEN';
import * as TREATMENT from './TREATMENT';
import * as RESEP from './RESEP';
import * as BILLING from './BILLING';
import * as SETTING_KASIR from './SETTING_KASIR';
import * as LAPORAN from './LAPORAN';

export const API = Object.assign({}, {
    AUTHENTICATION: AUTHENTICATION,
    SETUP_DATA: SETUP_DATA,
    PENDAFTARAN_PASIEN: PENDAFTARAN_PASIEN,
    PELAYANAN_PASIEN: PELAYANAN_PASIEN,
    TREATMENT: TREATMENT,
    RESEP: RESEP,
    SETTING_KASIR: SETTING_KASIR,
    BILLING: BILLING,
    LAPORAN: LAPORAN,
})