import * as SETUP_DOKTER from './SETUP_DOKTER';
import * as SETUP_TARIF from './SETUP_TARIF';
import * as SETUP_OBAT from './SETUP_OBAT';
import * as SETUP_CARA_PAKAI_OBAT from './SETUP_CARA_PAKAI_OBAT';
import * as SETUP_MARKETING from './SETUP_MARKETING';

export const API = Object.assign({}, {
    SETUP_DOKTER: SETUP_DOKTER,
    SETUP_TARIF: SETUP_TARIF,
    SETUP_OBAT: SETUP_OBAT,
    SETUP_CARA_PAKAI_OBAT: SETUP_CARA_PAKAI_OBAT,
    SETUP_MARKETING: SETUP_MARKETING,
})